// Rich card data with flavor text, ability descriptions, traits, and art descriptions

export interface CardInfo {
  name: string;
  type: 'asset' | 'event' | 'skill';
  class: string;
  cost?: number;
  slot?: string;
  traits: string[];
  ability: string;
  flavor: string;
  skillIcons: string; // e.g. "MGT WIT" or "WILD x2"
  vitality?: number;
  clarity?: number;
  art: 'pistol' | 'shield' | 'companion' | 'coat' | 'monocle' | 'journal' | 'engine'
    | 'pocketwatch' | 'ward' | 'cat' | 'blade' | 'bomb' | 'toolkit' | 'satchel'
    | 'coin' | 'watch' | 'stance' | 'repair' | 'eureka' | 'hypothesis'
    | 'timeshift' | 'quickthink' | 'lucky' | 'scrounge'
    | 'determination' | 'sharpmind' | 'bruteforce' | 'reflexes' | 'courage';
}

export const CARD_DATA: Record<string, CardInfo> = {
  // === GUARDIAN (Blue) ===
  asset_steam_pistol: {
    name: 'Steam Pistol',
    type: 'asset',
    class: 'guardian',
    cost: 3,
    slot: 'Hand',
    traits: ['Item', 'Weapon', 'Firearm'],
    ability: 'Fight. +1 Might, +1 damage.\nUses (4 ammo).',
    flavor: '"The recoil rattles your teeth, but nothing rattles a Clockwork Soldier quite like a brass slug."',
    skillIcons: 'MGT',
    art: 'pistol',
  },
  asset_brass_shield: {
    name: 'Brass Shield',
    type: 'asset',
    class: 'guardian',
    cost: 2,
    slot: 'Hand',
    traits: ['Item', 'Armor'],
    ability: 'Soak: 3 damage.',
    flavor: '"Forged from the Queen\'s own scrapheap. It bears the dent of a hundred croquet mallets."',
    skillIcons: 'MGT',
    vitality: 3,
    art: 'shield',
  },
  asset_clockwork_companion: {
    name: 'Clockwork Companion',
    type: 'asset',
    class: 'guardian',
    cost: 4,
    slot: 'Ally',
    traits: ['Ally', 'Automaton'],
    ability: 'After you defeat an enemy: Heal 1 damage from Clockwork Companion.',
    flavor: '"It doesn\'t speak, but its loyalty is wound as tight as its springs."',
    skillIcons: 'MGT RES',
    vitality: 3,
    clarity: 1,
    art: 'companion',
  },
  asset_reinforced_coat: {
    name: 'Reinforced Coat',
    type: 'asset',
    class: 'guardian',
    cost: 1,
    slot: 'Body',
    traits: ['Item', 'Armor'],
    ability: 'Soak: 2 damage, 1 horror.',
    flavor: '"Lined with brass plates and the stubborn refusal to fall down."',
    skillIcons: 'RES',
    vitality: 2,
    clarity: 1,
    art: 'coat',
  },
  // === SEEKER (Amber) ===
  asset_magnifying_monocle: {
    name: 'Magnifying Monocle',
    type: 'asset',
    class: 'seeker',
    cost: 1,
    slot: 'Accessory',
    traits: ['Item', 'Tool'],
    ability: '+1 Wit while investigating.',
    flavor: '"The lens reveals what the naked eye refuses to see — which is, frankly, most of Wonderland."',
    skillIcons: 'WIT',
    art: 'monocle',
  },
  asset_research_journal: {
    name: 'Research Journal',
    type: 'asset',
    class: 'seeker',
    cost: 2,
    slot: 'Hand',
    traits: ['Item', 'Tome'],
    ability: 'Exhaust: Draw 2 cards, then discard 1 card from hand.',
    flavor: '"Page 47: The gears turn counterclockwise on Tuesdays. Page 48: There are no Tuesdays."',
    skillIcons: 'WIT WILD',
    art: 'journal',
  },
  asset_analytical_engine: {
    name: 'Analytical Engine',
    type: 'asset',
    class: 'seeker',
    cost: 3,
    slot: 'Arcane',
    traits: ['Item', 'Clockwork'],
    ability: 'Investigate. +2 Wit for this investigation.',
    flavor: '"Babbage would weep with joy. Or possibly terror. In Wonderland, they\'re the same thing."',
    skillIcons: 'WIT x2',
    art: 'engine',
  },
  // === MYSTIC (Purple) ===
  asset_enchanted_pocket_watch: {
    name: 'Enchanted Pocket Watch',
    type: 'asset',
    class: 'mystic',
    cost: 3,
    slot: 'Arcane',
    traits: ['Spell', 'Clockwork'],
    ability: 'Investigate using Resolve instead of Wit.\nUses (3 charges).',
    flavor: '"Time is an illusion. The watch merely makes the illusion useful."',
    skillIcons: 'RES',
    art: 'pocketwatch',
  },
  asset_mirror_ward: {
    name: 'Mirror Ward',
    type: 'asset',
    class: 'mystic',
    cost: 2,
    slot: 'Arcane',
    traits: ['Spell'],
    ability: 'Exhaust: Cancel 1 horror dealt to you.',
    flavor: '"The looking-glass reflects not what is, but what should be — a world without fear."',
    skillIcons: 'RES GRC',
    art: 'ward',
  },
  asset_cheshire_familiar: {
    name: 'Cheshire Familiar',
    type: 'asset',
    class: 'mystic',
    cost: 3,
    slot: 'Ally',
    traits: ['Ally', 'Creature'],
    ability: 'Exhaust: Look at the top card of the encounter deck.',
    flavor: '"It grins whether the news is good or bad. That\'s the trouble with cats."',
    skillIcons: 'RES WILD',
    clarity: 3,
    art: 'cat',
  },
  // === ROGUE (Emerald) ===
  asset_spring_blade: {
    name: 'Spring-Loaded Blade',
    type: 'asset',
    class: 'rogue',
    cost: 2,
    slot: 'Hand',
    traits: ['Item', 'Weapon', 'Melee'],
    ability: 'Fight. +1 Might. If succeed by 2+, deal +1 damage.',
    flavor: '"A flick of the wrist, a click of the spring, and the conversation ends decisively."',
    skillIcons: 'GRC MGT',
    art: 'blade',
  },
  asset_smoke_bomb: {
    name: 'Smoke Bomb',
    type: 'asset',
    class: 'rogue',
    cost: 1,
    traits: ['Item', 'Gadget'],
    ability: 'Discard: Disengage from all enemies. They cannot engage you until end of round.',
    flavor: '"Disappearing is easy. The hard part is remembering where you reappear."',
    skillIcons: 'GRC x2',
    art: 'bomb',
  },
  asset_thieves_toolkit: {
    name: "Thief's Toolkit",
    type: 'asset',
    class: 'rogue',
    cost: 3,
    slot: 'Hand',
    traits: ['Item', 'Tool', 'Illicit'],
    ability: 'Investigate using Grace instead of Wit. If you succeed, gain 1 Gear.',
    flavor: '"Every lock in Wonderland has a key. This kit has all of them."',
    skillIcons: 'GRC WIT',
    art: 'toolkit',
  },
  // === SURVIVOR (Red) ===
  asset_leather_satchel: {
    name: 'Leather Satchel',
    type: 'asset',
    class: 'survivor',
    cost: 1,
    slot: 'Body',
    traits: ['Item'],
    ability: 'Soak: 2 damage, 2 horror.',
    flavor: '"It carries everything you need and nothing you want. Rather like life in Wonderland."',
    skillIcons: 'RES',
    vitality: 2,
    clarity: 2,
    art: 'satchel',
  },
  asset_lucky_coin: {
    name: 'Lucky Coin',
    type: 'asset',
    class: 'survivor',
    cost: 1,
    slot: 'Accessory',
    traits: ['Item', 'Charm'],
    ability: 'Exhaust after drawing a chaos token: +1 to your skill value.',
    flavor: '"Heads you win, tails you survive. It hasn\'t come up tails yet."',
    skillIcons: 'WILD',
    art: 'coin',
  },
  // === NEUTRAL ===
  asset_pocket_watch: {
    name: 'Pocket Watch',
    type: 'asset',
    class: 'neutral',
    cost: 1,
    slot: 'Accessory',
    traits: ['Item', 'Clockwork'],
    ability: 'Exhaust and discard: Gain 2 additional actions this turn.',
    flavor: '"Time is the most valuable currency in Wonderland. Spend it wisely."',
    skillIcons: 'WILD',
    art: 'watch',
  },
  // === EVENTS ===
  event_defensive_stance: {
    name: 'Defensive Stance',
    type: 'event',
    class: 'guardian',
    cost: 1,
    traits: ['Tactic'],
    ability: 'Fast. +2 Might until end of phase.',
    flavor: '"Stand your ground. The gears will not move you if you refuse to be moved."',
    skillIcons: 'MGT GRC',
    art: 'stance',
  },
  event_emergency_repair: {
    name: 'Emergency Repair',
    type: 'event',
    class: 'guardian',
    cost: 1,
    traits: ['Repair'],
    ability: 'Heal 2 damage from an asset you control.',
    flavor: '"A little solder, a firm hand, and the absolute refusal to let good machinery die."',
    skillIcons: 'RES',
    art: 'repair',
  },
  event_eureka: {
    name: 'Eureka!',
    type: 'event',
    class: 'seeker',
    cost: 0,
    traits: ['Insight'],
    ability: 'Fast. After you succeed at an investigation: Draw 1 card.',
    flavor: '"The connections snapped together like clockwork — because in Wonderland, they literally were."',
    skillIcons: 'WIT WILD',
    art: 'eureka',
  },
  event_working_hypothesis: {
    name: 'Working Hypothesis',
    type: 'event',
    class: 'seeker',
    cost: 2,
    traits: ['Insight'],
    ability: 'Discover 1 Curiosity at your location without a skill test.',
    flavor: '"I don\'t need to prove it. I merely need to be right."',
    skillIcons: 'WIT x2',
    art: 'hypothesis',
  },
  event_temporal_shift: {
    name: 'Temporal Shift',
    type: 'event',
    class: 'mystic',
    cost: 1,
    traits: ['Spell'],
    ability: 'Fast. Remove 1 Chaos from a card in play.',
    flavor: '"The clock hands stuttered, wound backwards, and the doom that was became the doom that wasn\'t."',
    skillIcons: 'RES x2',
    art: 'timeshift',
  },
  event_quick_thinking: {
    name: 'Quick Thinking',
    type: 'event',
    class: 'rogue',
    cost: 0,
    traits: ['Trick'],
    ability: 'Fast. After you evade an enemy: Gain 1 action this turn.',
    flavor: '"While they\'re looking left, you\'re already gone right."',
    skillIcons: 'GRC WILD',
    art: 'quickthink',
  },
  event_lucky_break: {
    name: 'Lucky Break',
    type: 'event',
    class: 'survivor',
    cost: 1,
    traits: ['Fortune'],
    ability: 'Fast. After you fail a skill test: +2 to your skill value. (May change failure to success.)',
    flavor: '"Some call it luck. Others call it a suspicious statistical anomaly."',
    skillIcons: 'WILD x2',
    art: 'lucky',
  },
  event_scrounge: {
    name: 'Scrounge',
    type: 'event',
    class: 'survivor',
    cost: 0,
    traits: ['Fortune'],
    ability: 'Return a level 0 card from your discard to your hand.',
    flavor: '"One person\'s rubbish is another person\'s salvation. Wonderland taught me that."',
    skillIcons: 'RES WIT',
    art: 'scrounge',
  },
  // === SKILLS ===
  skill_determination: {
    name: 'Determination',
    type: 'skill',
    class: 'neutral',
    traits: ['Innate'],
    ability: 'Commit to a skill test for +1 Resolve, +1 Wild.',
    flavor: '"The world bends for those who refuse to break."',
    skillIcons: 'RES WILD',
    art: 'determination',
  },
  skill_sharp_mind: {
    name: 'Sharp Mind',
    type: 'skill',
    class: 'neutral',
    traits: ['Innate'],
    ability: 'Commit to a skill test for +1 Wit, +1 Wild.',
    flavor: '"In a land of nonsense, reason is the sharpest weapon."',
    skillIcons: 'WIT WILD',
    art: 'sharpmind',
  },
  skill_brute_force: {
    name: 'Brute Force',
    type: 'skill',
    class: 'neutral',
    traits: ['Innate'],
    ability: 'Commit to a skill test for +1 Might, +1 Wild.',
    flavor: '"Sometimes the answer to \'how?\' is simply \'harder.\'"',
    skillIcons: 'MGT WILD',
    art: 'bruteforce',
  },
  skill_quick_reflexes: {
    name: 'Quick Reflexes',
    type: 'skill',
    class: 'neutral',
    traits: ['Innate'],
    ability: 'Commit to a skill test for +1 Grace, +1 Wild.',
    flavor: '"Between thought and action, there is no gap."',
    skillIcons: 'GRC WILD',
    art: 'reflexes',
  },
  skill_unexpected_courage: {
    name: 'Unexpected Courage',
    type: 'skill',
    class: 'neutral',
    traits: ['Innate'],
    ability: 'Commit to any skill test for +2 Wild.',
    flavor: '"Bravery is not the absence of fear. It is the clockwork heart that keeps ticking regardless."',
    skillIcons: 'WILD x2',
    art: 'courage',
  },
};
